### ISSUE TITLE
Voyager with kotlin-routing，how to get the Screen through the path

### ISSUE THREAD

**Issue by sceneren** [programadorthi/kotlin-routing#5]
```
val mineRouter = routing(rootPath = RoutePath.Mine.ROUTER, parent = mainRouting) {

    install(Resources)

    screen(path = RoutePath.Mine.NOTICE_SCREEN.routerPath()) {
        if(isLogin){
            NoticeScreen
        }else{
            // todo jump to LoginScreen
        }

    }
}
```

My LoginScreen is in another module, and I don't know how to get the LoginScreen through the path. Or is there another way to achieve it?

**Comment by programadorthi** [comment]
Hey @sceneren you can redirect to login screen since it exists in the routing graph.
So putting your login screen to `mainRouting` you can do:

```kotlin
val mainRouting = routing {
    screen(path = "/login") {
        LoginScreen()
    }
}

val mineRouting = routing(parent = mainRouting) {
    screen(path = "/notice") {
        if(isLogin){
            NoticeScreen
        }else{
            // redirect starts a coroutine and not execute immediatelly
            call.redirectToPath(path = "/login")
            // Well, shows a loading while not redirecting
            LoadingScreen()
        }
    }
}
```

Also there is an `auth` module that take care of authentication and authorization to routes. [Here ](https://github.com/programadorthi/kotlin-routing/blob/758aa48e7ef0252e6131b3436e2a05b61baf48cc/auth/common/test/dev/programadorthi/routing/auth/AuthTest.kt#L241)is a test that when trying to access a route and not authenticated the user will be redirected to login page

**Comment by sceneren** [comment]
thx
